### ISSUE TITLE
Feature request: Need support for includeBuild

### ISSUE THREAD

**Issue by rougsig** [dropbox/AffectedModuleDetector#100]
More details about includeBuild [here](https://docs.gradle.org/current/userguide/composite_builds.html)

Include build can be used as dependency, but for gradle that kind of dependency is external dependency.
[ProjectGraph](https://github.com/dropbox/AffectedModuleDetector/blob/main/affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/ProjectGraph.kt) can't work correct with includeBuild dependencies. For ProjectGraph includeBuild dependencies is external dependencies, not project dependencies. In that case not all modules can be found, and marked as unknownFiles.

**Comment by digitalbuddha** [comment]
Sounds interesting, How would we get the git data for the external build? We would need it to find which files are changed.

**Comment by rougsig** [comment]
Sample https://github.com/rougsig/AffectedModuleDetector

I've add failing test to includeBuild to that file `sample/include-util/common/src/test/java/com/dropbox/detector/sample_util/ExampleUnitTest.kt`. Run task for check. Task was green. 

[logs](https://github.com/rougsig/AffectedModuleDetector/blob/main/sample/output/output.log)
```
[INFO] [amd] unknownFiles: [sample/build.gradle, sample/include-util/common/src/test/java/com/dropbox/detector/sample_util/ExampleUnitTest.kt], changedProjects: [], buildAll: false
```

In gradle dependencies to module in includeBuild realised like external dependency.  More info can be found [here](https://docs.gradle.org/current/userguide/composite_builds.html#included_build_declaring_substitutions).
Like [that](https://github.com/rougsig/AffectedModuleDetector/blob/main/sample/sample-app/build.gradle#L46): `implementation "com.example.includeutil:common"`.

---

Expected behaviour is:

Project structure is:
`app -> utils-module (in includeBuild)`

Change in utils-module (in includeBuild).
Test will be executed for: app and utils-module (in includeBuild)

**Comment by rougsig** [comment]
To find module from include build, we need to know group of that module.

I can try to make PR with that logic, but it have one problem. We need to register group id and path of include build.

**Comment by joshafeinberg** [comment]
Sorry for the delay here but can you explain what you mean by "We need to register group id and path of include build" @rougsig? Are you saying that we would need to have them manually state any included builds?

I've played around with this a bit and it seems like the only way to get what included builds programmatically is to do `gradle.includedBuilds` but then we still don't get information of what dependencies those are replacing. I'm just not sure if this is feasible with the current gradle system

**Comment by rougsig** [comment]
I've implemented my own version of affected-module-detector with includeBuild support. Actually affected-module-detecktor should resolve dependencies, not iterate by them as now.
