### ISSUE TITLE
AffectedModuleDetectorPlugin is eagerly creating tasks at configuration time

### ISSUE THREAD

**Issue by mcumings** [dropbox/AffectedModuleDetector#115]
This plugin still needs to be updated to support the Gradle task configuration avoidance APIs documented here:

https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

Some examples of the use of the old/wrong APIs can be found in `filterAndroidTests`:
```
    private fun filterAndroidTests(project: Project) {
        val tracker = DependencyTracker(project, null)
        project.tasks.all { task ->
        ...
```
...and `filterJvmTests`:
```
        project.tasks.withType(Test::class.java) { task ->
            AffectedModuleDetector.configureTaskGuard(task)
        }
```

As a result of the above, our large project is eagerly creating thousands of testing tasks at configuration time.

The [migration guide](https://docs.gradle.org/current/userguide/task_configuration_avoidance.html#sec:task_configuration_avoidance_migration_guidelines) may be useful as a resource.

**Comment by handstandsam** [comment]
Thanks, we are aware of this.  I'm seeing a similar 10 second configuration hit on a very large project.
`` `
Plugin | 0.122s | (9.992s total) | Applied to 1 project | 2628 tasks created
```

We are happy to take contributions on this, but this is something we plan to look into in the coming months.  Thank you!

**Comment by mcumings** [comment]
Awesome.  Thanks, @joshafeinberg !
