### ISSUE TITLE
Build failure for task `createDebugAndroidTestApkListingFileRedirect` upon upgrading to `gradle plugin 7.1.2`

### ISSUE THREAD

**Issue by ilynehan** [dropbox/AffectedModuleDetector#125]
Hello! 

I am noticing failures when running `./gradlew assembleAffectedAndroidTests ...` when updating gradle plugin to version 7.1.2. It looks like the task `createDebugAndroidTestApkListingFileRedirect` fails for modules that are marked to skip apk generation. 

Here's the failure output:
```
A problem was found with the configuration of task ':lib:core:createStandardDebugAndroidTestApkListingFileRedirect' (type 'ListingFileRedirectTask').
  - In plugin 'com.android.internal.version-check' type 'com.android.build.gradle.internal.tasks.ListingFileRedirectTask' property 'listingFile' specifies file '/Users/runner05/actions-runner/_work/android/android/lib/core/build/outputs/apk/androidTest/standard/debug/output-metadata.json' which doesn't exist.
```

**Comment by maxkohne** [comment]
Any updates on this? We had to disable this library for the time being

**Comment by joshafeinberg** [comment]
I've updated the project to 7.1.2 and our sample app as well as our full app passes. Please update to the `0.1.5-SNAPSHOT` version to confirm the fixes

 If you are having issues can you please post a build with the `--stacktrace` option so we can better debug

**Comment by joshafeinberg** [comment]
Going to close this, feel free to reopen the issue with the stacktrace if you are still seeing problems with the latest version
