### ISSUE TITLE
Add an option to exclude jvm test paths

### ISSUE THREAD

**Issue by shanio** [dropbox/AffectedModuleDetector#186]
Hey,

Could it be possible to add support to exclude certain path(s) from jvm test execution?

There is a `exclude(Iterable<String> excludes)` function  in `org.gradle.api.tasks.testing.Test` class for it.  

**Use case:**
We need it to avoid running e.g. [paparazzi](https://github.com/cashapp/paparazzi) screenshot tests as part of main unit test task launched by `runAffectedUnitTests` task.

Up until now we use command line parameter:

`-PexcludeTests="**/screenshots/**, **/another_excluded_path/**"` That is being read and applied in `testOptions.unitTest` block

**Comment by joshafeinberg** [comment]
Hey,

So AMD is meant to be a general tool for finding affected modules. We include helpers for the tests but we don't actually require that the tool runs tests (see people using it with linters for instance). You can use the custom tooling to build this in if you don't want it to touch the command line

```
customTasks = [
        new AffectedModuleConfiguration.CustomTask(
            "runAffectedTestsAndIgnorePaparazzi",
            "runAffectedUnitTests -PexcludeTests=\"**/screenshots/**, **/another_excluded_path/**\"",
            "Run static analysis tool without auto-correction by Impact analysis"
        )
    ]
```

But I don't think we will support actually editing which tests run as thats a bit beyond the scope of this library
