### ISSUE TITLE
Assemble only affected Apps in multimodle project

### ISSUE THREAD

**Issue by wartingep** [dropbox/AffectedModuleDetector#195]
On our gradle project we have several apps and lots of modules. Is there any way to only assemble the APKs of affected apps?

**Comment by joshafeinberg** [comment]
Yes, you can use `AffectedModuleDetector.isProjectAffected(subproject)` to create a custom task and use that to decide if your project should build. So you could see `AffectedModuleDetector.isProjectAffected("app1")` and `AffectedModuleDetector.isProjectAffected("app2")` and if only the first one returns true then you can build `app2` only
