### ISSUE TITLE
Dry run of gradle cmd

### ISSUE THREAD

**Issue by EllySmore** [dropbox/AffectedModuleDetector#225]
Hello! 
I wonder if it is possible to run the command to get a list of affected modules below without executing the tests. 
I'm using `flank` for UI testing and I want to add the affected module directories to the `test_targets`. 
Same for unit tests. 
Thank you! 

```
./gradlew runAffectedUnitTests -Paffected_module_detector.enable -Paffected_module_detector.changedProjects
```

**Comment by joshafeinberg** [comment]
How we do this is we have a custom task for `flank` and use `AffectedModuleDetector.isProjectAffected(subproject)` to decide if we need to include that. We then export the results of that task to a file and then read that file from command line to know which ones we need.

Something like this

```
val paths = LinkedHashSet<String>()

rootProject.subprojects { subproject ->
    if (AffectedModuleDetector.isProjectAffected(subproject)) {
         val androidTestTask = getAmdExtension(subproject)?.runAndroidTestTask
    }
}
```
