### ISSUE TITLE
Sample project fails to compile

### ISSUE THREAD

**Issue by zsperske** [dropbox/AffectedModuleDetector#226]
Cannot find 0.2.2-SNAPSHOT.

**Comment by imohsenb** [comment]
Hi, before running the AMD command you need to either publish the lib to your local maven through the following command on root of the project:
```
./gradlew :affectedmoduledetector:publishToMavenLocal
```
Or change the dependency version to one that is available in maven central, like **0.2.1**  inside `buildSrc > build.gradle.kts`.

you can also find [more info here](https://github.com/dropbox/AffectedModuleDetector#using-the-sample-project)

**Comment by joshafeinberg** [comment]
Yep, you need to publish to your local if you want to test with the local code there. otherwise you can change the sample app to hit the latest public release and then you can skip that step.
