### ISSUE TITLE
Task 'runAffectedUnitTests' not found in root project

### ISSUE THREAD

**Issue by nhaarman** [dropbox/AffectedModuleDetector#23]
Whenever I apply the plugin to a project and run the `./gradlew runAffectedUnitTests -Paffected_module_detector.enable` command, I get the following error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'runAffectedUnitTests' not found in root project 'my-project'.
```

Running `./gradle tasks` or `./gradlew tasks -Paffected_module_detector.enable` results in no tasks added by this plugin either.

I have tried with multiple Android/Java only projects which all have different configurations, but all come up with the same results. I even copy pasted this entire block into the root build.gradle (thus having two `buildscript` blocks) to no success.

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.dropbox.affectedmoduledetector:affectedmoduledetector:0.1.0"
  }
}
apply plugin: "com.dropbox.affectedmoduledetector"
```

**Comment by digitalbuddha** [comment]
hi @nhaarman apologies I never did a release due to wanting to move config block to be module specific. It should exist in the snapshot. I'm working on the improved config block right now and will have a full release today

**Comment by nhaarman** [comment]
Ahh that explains! No worries!

**Comment by digitalbuddha** [comment]
0.1.1-SNAPSHOT was just pushed, 0.1.2 will be out sometime tomorrow

**Comment by fabiocarballo** [comment]
@digitalbuddha did you end up publishing it? I couldn't find it.

**Comment by nhaarman** [comment]
`0.1.1-SNAPSHOT` can be resolved for me, but it doesn't seem that `./gradlew runAffectedUnitTests -Paffected_module_detector.enable` only runs affected unit tests, it runs all 🤔

**Comment by digitalbuddha** [comment]
There should be a log file created. Could you verify that all modules were not affected during your execution? I have a free day tomorrow and will validate myself on the sample.

**Comment by nhaarman** [comment]
I started a new project and added one library module. Applying the plugin and running the command results in only this in the logs 🤔 :

```
[INFO] [amd] Modules provided: null
[INFO] [amd] Using real detector
```

**Comment by digitalbuddha** [comment]
I think my last change was racy, we've seen this before where the modules tasks did not exist before we ran our plugin task creation. Thanks for reporting I'll replicate and fix in am.

**Comment by digitalbuddha** [comment]
need 1 more fix to land, I verified in the sample #27 both a non working behavior and now a working one. The issue was around short circuiting custom logic we had internally. I expect a review by end of week and will release new snapshot then. Thank you for bearing with us in the early days :-D

**Comment by nhaarman** [comment]
No problem! If you need anything else let me know!

**Comment by digitalbuddha** [comment]
new snapshot is up, will verify internally then do a real release

**Comment by nhaarman** [comment]
When I cloned the repository and published the snapshot locally, the plugin seemed to work on my real-life project! 
(I couldn't get the published snapshot to work for some reason)

**Comment by digitalbuddha** [comment]
Plugin publishing seems to escape my skill set. I'll keep at it! Thanks for feedback

**Comment by digitalbuddha** [comment]
I forgot to chmod the release script, running now #29

**Comment by nhaarman** [comment]
@digitalbuddha Will there be a release for these fixes?
