### ISSUE TITLE
Custom task executed on all modules instead of only affected modules

### ISSUE THREAD

**Issue by ss0930** [dropbox/AffectedModuleDetector#230]
The following config executes `lintRelease` for all modules, not just affected modules. Any idea what the issue with the config could be?

`./gradlew lintReleaseByImpact -Paffected_module_detector.enable -Paffected_module_detector.changedProjects`

root `build.gradle`

```
apply plugin: "com.dropbox.affectedmoduledetector"

import com.dropbox.affectedmoduledetector.AffectedModuleConfiguration

affectedModuleDetector {
  baseDir = "${project.rootDir}"
  logFilename = "output.log"
  logFolder = "${project.rootDir}/affectedModuleDetector"
  specifiedBranch = "main"
  compareFrom = "SpecifiedBranchCommitMergeBase"
  customTasks = [
          new AffectedModuleConfiguration.CustomTask(
                  "lintReleaseByImpact",
                  "lintByImpact",
                  "Run lint by Impact analysis"
          )
  ]
}
```

```
allprojects {
  tasks.register("lintByImpact") {
    def lintReleaseTask = it.project.tasks.findByName("lintRelease")
    if (lintReleaseTask != null) {
      it.dependsOn(lintReleaseTask)
    }
  }
}
```

**Comment by joshafeinberg** [comment]
You shouldn't need that second block. We will create that `lintByImpact` task for you and internally check if the module is affected. If you delete that this should work properly but feel free to reopen

**Comment by ss0930** [comment]
> You shouldn't need that second block. We will create that `lintByImpact` task for you and internally check if the module is affected. If you delete that this should work properly but feel free to reopen

```
allprojects {
  tasks.register("lintByImpact") {
    def lintReleaseTask = it.project.tasks.findByName("lintRelease")
    if (lintReleaseTask != null) {
      it.dependsOn(lintReleaseTask)
    }
  }
}
```

This block is added to have `lintByRelease` act as a wrapper task around `lintRelease`. This is done because not every module is configured for lint and may not have `lintRelease` task. So if a module is affected/changed but does not have lint, then gradle will try to execute lintRelease for that module but fail due to no task available

**Comment by joshafeinberg** [comment]
This is fixed by #233 and will be part of the next release

**Comment by ss0930** [comment]
@joshafeinberg when is the next release expected to be out?

**Comment by joshafeinberg** [comment]
Probably in the next week or two

**Comment by ss0930** [comment]
Is there a way to achieve this before the new release is out? Right now I am getting an error because not all modules have lint  and adding the second block causes task in all modules to be executed.

**Comment by ss0930** [comment]
Okay, found a work around using a check `AffectedModuleDetector.isProjectAffected(it.project)`

```
allprojects {
  tasks.register("lintByImpact") {
    def lintReleaseTask = it.project.tasks.findByName("lintRelease")
    if (lintReleaseTask != null && AffectedModuleDetector.isProjectAffected(it.project) {
      it.dependsOn(lintReleaseTask)
    }
  }
}
```
