### ISSUE TITLE
running all tests everytime

### ISSUE THREAD

**Issue by igorromcy** [dropbox/AffectedModuleDetector#232]
I'm running: `./gradlew runAffectedUnitTests -Paffected_module_detector.enable -Paffected_module_detector.changedProjects` and it is running all tests. 

I was expecting two modules to be affected only, any clue what could be the problem?

This is the configuration I'm using:

```
affectedModuleDetector {
    baseDir = "${project.rootDir}"
    specifiedBranch = "origin/master"
    compareFrom = "SpecifiedBranchCommitMergeBase"
    logFolder = "${project.rootDir}/output"
    logFilename = "affected_module_detector.log"
    includeUncommitted = false
    excludedModules = [
            "tests"
    ]
}
```

My output log: 
[INFO] [amd] Modules provided: null
[INFO] [amd] Using real detector with CHANGED_PROJECTS

**Comment by joshafeinberg** [comment]
You didn't really provide enough details here. I would guess your first problem is that you probably want specifiedBranch to be `master`, not `origin/master`. 

Also in your logs you can look at what git returned. You should see something like `running command git rev-parse master` and if you run that locally you can see what files it marked as changed. From there you can probably debug as to whats gone wrong. Going to close this but please if you plan on reopening provide additional details and do some local debugging to figure out your git issues
