### ISSUE TITLE
Weird behavior on git commands

### ISSUE THREAD

**Issue by igorromcy** [dropbox/AffectedModuleDetector#234]
Hey devs! 

I'm applying the AMD framework, but I'm facing a weird behavior: 
- When I debug the git commands looks like the hash commit that is being returned is not the expected one. 
- Even wrong and affecting more commits than I expected, I don't have any modules being recognized as affected.

by the way: I can see all the modules in that log list like this:
`[INFO] [amd] checking whether I should include :feature:blablabla and my answer is false
`

firsts lines of the log:

```
[INFO] [amd] Modules provided: null
[INFO] [amd] Using real detector with CHANGED_PROJECTS
[INFO] [amd] running command git rev-parse --abbrev-ref HEAD in /project
[INFO] [amd] Response: master
[INFO] [amd] running command git merge-base master TT-1141-AMD-Configuration-Fix in /project
[INFO] [amd] Response: 29303f8099ee18f8bac6025e8e5d610737e378e2
[INFO] [amd] running command git --no-pager diff --name-only -M95 HEAD..29303f8099ee18f8bac6025e8e5d610737e378e2 in /project
[INFO] [amd] Response: 
[INFO] [amd] checking whether I should include :feature:blablabla and my answer is false
....
```

Running locally my logs is only: 
```
[INFO] [amd] Modules provided: null
[INFO] [amd] Using real detector with CHANGED_PROJECTS
```
and it is running all the tests 

that's my config: 

```
affectedModuleDetector {
        baseDir = "${project.rootDir}"
        pathsAffectingAllModules = [
                "gradle/libs.versions.toml"
        ]
        specifiedBranch = "$System.env.BUILDKITE_BRANCH"
        compareFrom = "SpecifiedBranchCommitMergeBase"
        logFolder = "${project.rootDir}/output"
        logFilename = "affected_module_detector.log"
        includeUncommitted = false
        top = "HEAD"
        excludedModules = [
                "tests"
        ]
    }
```

**Comment by igorromcy** [comment]
@joshafeinberg @Evleaps, any ideas?

**Comment by joshafeinberg** [comment]
This still doesn't answer the issue in your last one. Also, please remember that I work on this in addition to my normal job so please do not tag the developers especially after just 6 minutes

> When I debug the git commands looks like the hash commit that is being returned is not the expected one.

Then make sure you are running the right `compareFrom`. You are currently using commit merge base so check out this doc (https://github.com/dropbox/AffectedModuleDetector#specifiedbranchcommit-vs-specifiedbranchcommitmergebase) to make sure you are running the right one. You can see in the logs the hash so you can just edit this, or try the other strategies, till you figure out the right one. We cannot provide support for each persons configuration.

> Even wrong and affecting more commits than I expected, I don't have any modules being recognized as affected.

Again, I'm not sure how I can help here without getting involved in your specific case. You can check the git logs to see which files changed (https://github.com/dropbox/AffectedModuleDetector/blob/main/affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetector.kt#L432) and then you can see why modules were selected or not

**Comment by igorromcy** [comment]
sure, will give a try, ty
