### ISSUE TITLE
Gradle 8.10 breaks AffectedModuleDetector dependentList tracking

### ISSUE THREAD

**Issue by mcumings** [dropbox/AffectedModuleDetector#260]
`DependencyTracker.dependentList` is a `Map<Project, Set<Project>>`.  This operates under the assumption that the `Project` equals/hashcode implementations uniquely identifies a single project instance.

In Gradle 8.10 it appears as though this assumption is now invalid, resulting in the same project (by path) being added as multiple keys in the `dependentList` map.  This then breaks subsequent `findAllDependents` lookups, resulting in the incorrect result that no modules are affected by a change.

**Comment by bddckr** [comment]
An issue was opened with Gradle: https://github.com/gradle/gradle/issues/30272

Work's already ongoing to work around that Gradle change: https://github.com/dropbox/AffectedModuleDetector/pull/257

**Comment by joshafeinberg** [comment]
Yes, should be fixed with #257
