### ISSUE TITLE
Allow dispatch various flows based on the type of changes?

### ISSUE THREAD

**Issue by MaTriXy** [dropbox/AffectedModuleDetector#30]
Hi,
Thanks for sharing this to the world. 

I would like to run different flows based on the package changed (for example) 
And have a default set running no matter what was the change (in addition).

Thanks.

**Comment by joshafeinberg** [comment]
Hello,

Sorry for the delay on responding to this. If this is still a feature that you wanted could you please give an example of what you are looking for?

If I'm understanding correct you want to, for example, if you see a change in `:my:custom:package` you want to do something and if you see a change in `:my:custom:package2` do something else? If so, this probably won't be something we build into this project. We do expose `AffectedModuleDetector.isProjectAffected(project)` so you could build your own custom plugin on top of AMD. That should also solve your secondary problem. You can view some samples in the repo here 

Let me know if that all makes sense
