### ISSUE TITLE
Unable to find method affectedTestConfiguration()

### ISSUE THREAD

**Issue by RowlandOti** [dropbox/AffectedModuleDetector#31]
I am running the sample app and changed the version to 0.1.0 since I do not able to access the snapshot version form all mavens. When trying to build the sample, I get the following build error:

![Desktop-screenshot (9)](https://user-images.githubusercontent.com/8356008/100841852-f2490380-3488-11eb-8bba-f5c89b12568c.png)

I get the same error when I try to integrate it to another project, as shown below:

![Desktop-screenshot (8)](https://user-images.githubusercontent.com/8356008/100841771-ce85bd80-3488-11eb-9130-c9dfb16399e5.png)

**Comment by digitalbuddha** [comment]
Hello! Could you kindly try using affectedmoduledetector/0.1.1-SNAPSHOT which is published in sonatypes snapshot repo https://oss.sonatype.org/content/repositories/snapshots/com/dropbox/affectedmoduledetector/affectedmoduledetector/0.1.1-SNAPSHOT/

**Comment by digitalbuddha** [comment]
if you are using the sample you're going to need to add "https://oss.sonatype.org/content/repositories/snapshots/" as a maven source. Normally we use the sample for integration once a full version is live (non snapshot). We hope to have a non snapshot version released this week. Pardon the early mess :-)

**Comment by RowlandOti** [comment]
Yeah, right. Including the snapshot maven works. No worries, it's a fairly new project so I understand. Hoping to contribute too, as it grows.
