### ISSUE TITLE
Not checking modules correctly

### ISSUE THREAD

**Issue by jonnycaley** [dropbox/AffectedModuleDetector#42]
Apologies in advance if i'm using the plugin wrong.

When running the plugin on my [experimentation project](https://github.com/jonnycaley/Hilt-Testing-Experimentation) it doesn't seem to be working correctly. If i make a change in a module that is an immediate dependency of the app module (either core or core-navigation) then the command `./gradlew runAffectedUnitTests -Paffected_module_detector.enable` works correctly.

However, if I make a change to a module that is a transitive dependency of core (e.g. feature-pokemondetail or feature-pokemonlist) then the output of the logs does not work correctly.

Feel free to clone my repo and try for yourself. Any help appreciated 😄 

<img width="734" alt="Screenshot 2020-12-10 at 09 36 01" src="https://user-images.githubusercontent.com/26006896/101754002-2c3e8900-3acb-11eb-9a30-80d2a9037ee5.png">
<img width="749" alt="Screenshot 2020-12-10 at 09 33 59" src="https://user-images.githubusercontent.com/26006896/101754009-2d6fb600-3acb-11eb-91c7-40af2d2f1d1c.png">

**Comment by chris-mitchell** [comment]
Thanks for the report.  Would you mind uploading the entire log output? That might have a clue as to what is going on.

**Comment by jonnycaley** [comment]
Sure! See attached

[transitive.log](https://github.com/dropbox/AffectedModuleDetector/files/5675533/transitive.log)
[non-transitive.log](https://github.com/dropbox/AffectedModuleDetector/files/5675542/non-transitive.log)

**Comment by jonnycaley** [comment]
Thanks for the fix! 

How am I able to test it? I'm currently using version `0.1.1-SNAPSHOT` as suggested [here](https://github.com/dropbox/AffectedModuleDetector/issues/31#issuecomment-737358147) as 0.1.0 not working. Will I have to wait for a new version of the library (e.g. 0.1.2) with this fix or am I able to test it out before hand?

**Comment by digitalbuddha** [comment]
0.1.1-SNAPSHOT should be updated in sonatypes snapshot repo. You might need to do `gradlew assemble --refresh-dependencies` to pull new version down

**Comment by jonnycaley** [comment]
Thanks! Works as expected now 😄
