### ISSUE TITLE
Exclude defined modules from being considered

### ISSUE THREAD

**Issue by jonnycaley** [dropbox/AffectedModuleDetector#51]
Proposal: Parse a list of module names into a configuration which **wont** be considered by the dependency decision making process, as well as the test apk building and running.

Please let me know of any objections, otherwise I will start the work for this in the upcoming days.

**Comment by digitalbuddha** [comment]
Do I understand it as a never build list? Sounds like a reasonable configuration if you want to add it. Thanks for contributing

**Comment by jonnycaley** [comment]
So you would be able to parse a list of modules in the configuration that you would not want to enable tests to be run for (for whatever reason) and then the `AffectedModuleDetector.kt` would be changed to something like this:
```
override fun shouldInclude(project: Project): Boolean {
        return (
            (project.isRoot || (
                affectedProjects.contains(project) &&
                    isProjectProvided2(project)
                )) && !config.excludedModules.contains(project.name)
            ).also {
            logger?.info(
                "checking whether I should include ${project.path} and my answer is $it"
            )
        }
    }
```

**Comment by jonnycaley** [comment]
Added [here](https://github.com/dropbox/AffectedModuleDetector/pull/54)
