### ISSUE TITLE
Fix link in README to AndroidX project

### ISSUE THREAD

**Issue by VictorIreri** [dropbox/AffectedModuleDetector#52]
### Issue
The link to the original AndroidX project in the README leads to a 404 Not Found error.
https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/buildSrc/src/main/kotlin/androidx/build/dependencyTracker

### Reason
This is because the `androidx-master-dev` branch was replaced by `androidx-main`:
https://android.googlesource.com/platform/frameworks/support/+/c19a44147515bcc4404409e27db5de4e6e9aa73c

### Solution
The link should be updated to:
https://android.googlesource.com/platform/frameworks/support/+/androidx-main/buildSrc/src/main/kotlin/androidx/build/dependencyTracker
\
\
Side note: I found this repo via [this Dropbox blog](https://dropbox.tech/mobile/revamping-the-android-testing-pipeline-at-dropbox) which also has the old link. 😉

**Comment by digitalbuddha** [comment]
Want to submit a fix and get some internet points?

**Comment by VictorIreri** [comment]
> Want to submit a fix and get some internet points?

I really do. 😁

**Comment by VictorIreri** [comment]
@digitalbuddha Please let me know if I did it right 🙂
