### ISSUE TITLE
Support ForkCommit with rebasing

### ISSUE THREAD

**Issue by kaeawc** [dropbox/AffectedModuleDetector#55]
"ForkCommit" as I understand it currently requires a merge commit in order to determine the parent branch. However if a project is practicing rebasing as a way of working and merging work, then there will be no merge commits. Not sure what the solution to this would be off the top of my head, just pointing out this is an issue.

**Comment by jonnycaley** [comment]
I would suggest using the `compareFrom = "SpecifiedBranchCommit"` configuration to define that you want to compare changes against another branch and the  `specifiedBranch = “master”` configuration to define the branch to compare against.

**Comment by joshafeinberg** [comment]
@kaeawc going to close this since it seems that the suggestion worked for you. let me know if you still need more help :)
