### ISSUE TITLE
Missing excludedModules

### ISSUE THREAD

**Issue by Zeyad-37** [dropbox/AffectedModuleDetector#58]
According to the docs, we can specify `excludedModules` while in the sample code its using version `0.1.2-SNAPSHOT` and the version available on maven central is `0.1.1`, any plans to release this new version ?? This is kinda blocking us from adopting this plugin, thx in advance.

**Comment by chris-mitchell** [comment]
Hi there - we've released version 0.1.2 which includes that feature.  It should be available on maven central shortly.  Please let us know if you have any issues.
