### ISSUE TITLE
Moving files occasionally results in missed modules

### ISSUE THREAD

**Issue by chris-mitchell** [dropbox/AffectedModuleDetector#60]
In changes with file moves, occasionally the detector doesn't catch that the move occurred and that affected modules should be run.  This can be seen in the log file when the `git diff` command is run.

**Comment by chris-mitchell** [comment]
In testing, `git --no-pager diff --name-only bc15f85feacb52ee53d16a8511f9fb020f8e6209` will show the entire set of changes, while `git --no-pager diff --name-only HEAD..bc15f85feacb52ee53d16a8511f9fb020f8e6209` does not. 

Adding `-M95` onto the command helps git figure out that files were moved - `git --no-pager diff --name-only HEAD..bc15f85feacb52ee53d16a8511f9fb020f8e6209 -M95`

**Comment by digitalbuddha** [comment]
What is significance of m95, can't find docs for it

**Comment by chris-mitchell** [comment]
It controls how sensitive git is when looking for renames - https://git-scm.com/docs/git-diff#Documentation/git-diff.txt--Mltngt
