### ISSUE TITLE
Plugin doesn't work for java services.

### ISSUE THREAD

**Issue by tinder-ravitejabonagiri** [dropbox/AffectedModuleDetector#70]
Hey Team, 

I am trying to apply the plugin for one of our repos which mainly consists of `java` libraries and applications. The libraries have `java-library` plugin applied. However, the applications have only `java` plugin applied. 

So the `affecttedModule` detector won't run the `tests` of applications as part of `runAffectedUnitTests` . 

I propose to change the implementation to support `java` applications as well. 

This can be achieved by changing this piece of code from :

```
`                val pluginIds = setOf("com.android.application", "com.android.library", "java-library", "kotlin")
                
                pluginIds.forEach { pluginId ->

                    if (pluginId == "java-library" || pluginId == "kotlin")`
                    .
                    .
                    .
                    }
```
                    
to 
```
                val pluginIds = setOf("com.android.application", "com.android.library", "java", "kotlin")

                pluginIds.forEach { pluginId ->

                    if (pluginId == "java" || pluginId == "kotlin")
                    .
                    .
                    .
                    
                    }
```

in [AffectedModuleDetectorPlugin](https://github.com/dropbox/AffectedModuleDetector/blob/main/affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedModuleDetectorPlugin.kt#L77) class. 

Also, what is the process for raising a PR? Thank you so much for this lovely library/plugin.

**Comment by digitalbuddha** [comment]
Hello! While that was never an original use case it sounds like a great addition. Prs are fairly easy, you'll need to sign the cla which is in the pr template. We love external contributors!

**Comment by antwan-flinkhub** [comment]
Hey, any update on when this will be merged?
Thanks

**Comment by changusmc** [comment]
> Hey, any update on when this will be merged?
> Thanks

We are still waiting for the author to sign the CLA.
