### ISSUE TITLE
runAffectedUnitTests -Paffected_module_detector.enable  fails on CI only 

### ISSUE THREAD

**Issue by antwan-flinkhub** [dropbox/AffectedModuleDetector#88]
Hey, 
this was mentioned before but in my case it's only failing on CI
When I run ./gradlew runAffectedUnitTests -Paffected_module_detector.enable  on Bitrise it fails in my project with error:

```
* What went wrong:
Could not evaluate onlyIf predicate for task ':module:testDebugUnitTest'.
> Nonzero exit value running git command.
```
the task is working fine locally 
My git project is setup on CI and i do git clone before invoking this command

**Comment by 6hundreds** [comment]
Experienced this stuff too at Bitrise. Perhaps you are using SpecificBranchCommit configuration with branch = {yourDevelopBranch} but your PRs is not targeted to develop, but in another branch. That's was a reason for me.

**Comment by vyshas** [comment]
@6hundreds we use bitrise as well and currently trialing this plugin. So does this mean that any branches that doesn't point to the branch mentioned in specificCommit will fail from running affected tests ?

**Comment by antwan-flinkhub** [comment]
@6hundreds yes we do have `specificBrancCommit` which point to develop but the PR is also pointing to develop

**Comment by shobande-femi** [comment]
Can you post the out of the log file produced by the plugin?

I struggled with this issue over the past couple of days. In my case, the specifiedBranch was absent from the working tree. (I use Github Actions and it clones the repo in some sort of minimalist fashion).
 
My solution was to run `git fetch origin develop:develop` right before `runAffectedUnitTests`

Note: in this case `develop` is the specifiedBranch. Replace with whatever branch you specified.

**Comment by joshafeinberg** [comment]
Hello, I think @shobande-femi pointed out what is probably going wrong. You need to make sure that your CI has access to the git tree that it needs. You can find a log with a more detailed error in your `logFolder/logFilename`

As this hasn't been updated in a few months I am going to close, please reopen or file a new ticket if you are still having issues
