### ISSUE TITLE
Publish plugin marker artifact 

### ISSUE THREAD

**Issue by gabrielittner** [dropbox/AffectedModuleDetector#89]
Could you publish a plugin marker artifact to maven central to make it possible to use the plugin like this without needing any extra config?

```
plugins {
    id "com.dropbox.affectedmoduledetector" version "..."
}
```

When you use the `java-gradle-plugin` and `maven-publish` together it should be created automatically. Here are the Gradle docs https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers

**Comment by joshafeinberg** [comment]
This will be fixed with the 0.1.5 release. right now it is available via snapshot
