### ISSUE TITLE
variantToTest is not implemented

### ISSUE THREAD

**Issue by michaelcarrano** [dropbox/AffectedModuleDetector#95]
I am playing around with this plugin and it seems like the `variantToTest` that is mentioned in the README isn't actually implemented.
```
affectedTestConfiguration{
   variantToTest = "debug" //default is debug
}
```
You can see `variantToTest` isn't defined in [AffectedTestConfiguration](https://github.com/dropbox/AffectedModuleDetector/blob/main/affectedmoduledetector/src/main/kotlin/com/dropbox/affectedmoduledetector/AffectedTestConfiguration.kt). However, you can see an example of this in the sample app [AffectedTasksPlugin](https://github.com/dropbox/AffectedModuleDetector/blob/main/sample/buildSrc/src/main/kotlin/com/dropbox/sample/tasks/AffectedTasksPlugin.kt#L13-L19)

To reproduce, you can try adding `variantToTest` in one of the sample/build.gradle files such as https://github.com/dropbox/AffectedModuleDetector/blob/main/sample/sample-app/build.gradle#L8-L10. I actually run into a compile error when I try to build after adding `variantToTest`.

I am working on making changes so this works but so far, still only seeing the tests for debug variant running.

I changed the `AffectedTestConfiguration` to:
```
open class AffectedTestConfiguration {

    var variantToTest : String = "debug"
    var assembleAndroidTestTask : String? = "assemble${variantToTest.capitalize()}AndroidTest"
    var runAndroidTestTask : String?  = "connected${variantToTest.capitalize()}AndroidTest"
    var jvmTestTask : String? = "test${variantToTest.capitalize()}UnitTest"


    companion object {
        const val name = "affectedTestConfiguration"
    }
}
```

Any pointers? Would love to make a PR with the fix.

**Comment by chris-mitchell** [comment]
Hi @michaelcarrano - oops, looks like the documentation and sample slipped with actual usage.  I'll fix that shortly. 

You should be able to use `assembleAndroidTestTask`, `runAndroidTestTask` and `jvmTestTask` to specify which tasks you want to run when the tests run for the given module.
